version: '3'

services:
  backend:
    build: ./backend 
    ports:
      - 3001:3001
    environment:
      - DB_USER=root
      - DB_PASS=pass
      - DB_NAME=sequelize_cli
      - DB_HOST=db 
      - JWT_SECRET=mysecret
    volumes:
      - ./backend:/app-backend
    container_name: sequelize_cli_backend
    restart: always
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    restart: always
    

